receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
  batch/test:

exporters:
  file:
    path: ./output.json
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
  telemetry:
    logs:
      level: debug
      initial_fields:
        service: apollo-demo
    metrics:
      level: detailed
      address: 0.0.0.0:8888
