receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
  batch/test:

exporters:
  file:
    path: ./output.json

  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
