receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 15s
    send_batch_size: 90

exporters:
  file:
    path: ./output.json
  logging:
    loglevel: debug

  prometheus:
    endpoint: 'localhost:9090'

  otlp:
    endpoint: 127.0.0.1:443
    tls:
      cert_file: ./certs/cert.pem
      key_file: ./certs/cert-key.pem

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
  telemetry:
    logs:
      level: debug
      initial_fields:
        service: apollo-demo
    metrics:
      level: detailed
      address: 0.0.0.0:8888
