headers:
  all:
    request:
      - propagate:
          named: "Authorization"
cors:
  origins:
    - http://localhost:3000
include_subgraph_errors:
  all: true
rhai:
  scripts: "./router-scripts"
  main: "main.rhai"
sandbox:
  enabled: true
homepage:
  enabled: false
supergraph:
  introspection: true
telemetry:
  metrics:
    otlp:
      # Either 'default' or a URL
      endpoint: default
      # Optional timeout in humatime form
      timeout: 2s
    prometheus:
      enabled: true
      listen: 127.0.0.1:9090
      path: /metrics
