headers:
  all:
    request:
      - propagate:
          named: "Authorization"
include_subgraph_errors:
  all: true
rhai:
  scripts: "./router-scripts"
  main: "main.rhai"
sandbox:
  enabled: true
homepage:
  enabled: false
supergraph:
  introspection: true
telemetry:
  metrics:
    otlp:
      # Either 'default' or a URL
      endpoint: default

      # Optional protocol. Only grpc is supported currently.
      # Setting to http will result in configuration failure.
      protocol: grpc

      # Optional Grpc configuration
      grpc:
        domain_name: "my.domain"
        key: ""
        ca: ""
        cert: ""
        metadata:
          foo: bar

      # Optional timeout in humatime form
      timeout: 2s
