headers:
  all:
    request:
      - propagate:
          named: 'Authorization'
cors:
  origins:
    - http://localhost:3000
include_subgraph_errors:
  all: true
rhai:
  scripts: './router-scripts'
  main: 'main.rhai'
sandbox:
  enabled: true
homepage:
  enabled: false
supergraph:
  introspection: true
telemetry:
  metrics:
    common:
      # (Optional, default to "apollo-router") Set the service name to easily find metrics related to the apollo-router in your metrics dashboards
      service_name: 'apollo-router'
    otlp:
      # Either 'default' or a URL
      endpoint: default
    prometheus:
      enabled: true
      listen: 0.0.0.0:9095
      path: /metrics
