federation_version: 2
subgraphs:
  subgraphdemo:
    routing_url: http://localhost:4001/
    schema:
      file: "./subgraph-demo/schema.graphql"
  subgraphuser:
    routing_url: http://localhost:4002/
    schema:
      file: "./subgraph-user/schema.graphql"
