federation_version: 2
subgraphs:
  subgraph-demo:
    routing_url: http://localhost:4001/
    schema:
      file: './subgraph-demo/schema.graphql'
  subgraph-user:
    routing_url: http://localhost:4002/
    schema:
      file: './subgraph-user/schema.graphql'
