federation_version: 2
subgraphs:
  subgraph-product:
    routing_url: http://localhost:4001/
    schema:
      file: "./subgraph-product/schema.graphql"
  subgraph-user:
    routing_url: http://localhost:4002/
    schema:
      file: "./subgraph-user/schema.graphql"
