name: Deploy Subgraph Server

on:
  workflow_call:
    inputs:
      subgraph_name:
        description: Subgraph name in Studio
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.subgraph_name }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Check working directory
        run: ls -la && pwd
      - run: echo "Run Deploy steps to deploy Subgraph Server"
