name: User Subgraph CI

on:
  push:
    branches: ["main"]
    paths:
      - "subgraph-user/**"
  pull_request:
    branches: ["main"]
    paths:
      - "subgraph-user/**"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      subgraph_name: subgraph-user

  check:
    needs: build
    uses: ./.github/workflows/_check.yml
    secrets: inherit
    with:
      subgraph_name: subgraph-user

  deploy:
    needs: check
    uses: ./.github/workflows/_deploy.yml
    with:
      subgraph_name: subgraph-user

  publish:
    needs: deploy
    uses: ./.github/workflows/_publish.yml
    secrets: inherit
    with:
      subgraph_name: subgraph-user
      routing_url: http://localhost:4002/
