# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: User Subgraph CI

on:
  push:
    branches: ["main"]
    paths:
      - "subgraph-user/**"
  pull_request:
    branches: ["main"]
    paths:
      - "subgraph-user/**"

jobs:
  setup:
    uses: ./.github/workflows/build.yml
    with:
      subgraph_name: subgraph-user

  check:
    needs: setup
    uses: ./.github/workflows/check.yml
    secrets: inherit
    with:
      subgraph_name: subgraph-user

  deploy:
    needs: check
    uses: ./.github/workflows/deploy.yml
    with:
      subgraph_name: subgraph-user

  publish:
    needs: deploy
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      subgraph_name: subgraph-user
      routing_url: http://localhost:4002/
